#!/bin/bash
#Mime types y extensiones
xdg-mime install source/azpazeta-mime.xml
xdg-mime install source/azpazeta-text-mime-xml
xdg-mime default Azpazeta.desktop application/x-azpazeta-savefile
xdg-mime default Azpazeta.desktop text/x-azpazeta-savefile
#Librerias

#cp source/azpazeta-libs.conf /etc/ld.so.conf.d/
#ldconfig

